### ISSUE TITLE
gopass insert broken in 1.10 and appends a new line when reading from stdin

### ISSUE THREAD

**Issue by cburgmer** [gopasspw/gopass#1573] opened 2020-09-07 13:38 UTC
### Summary

When creating passwords from outside gopass and passing them via STDIN, in gopass 1.10.1 a newline is appended before the string, fundamentally changing the credentials.

### Steps To Reproduce
```
$ echo hello | gopass insert mystore/myvalue
$ gopass show -f mystore/myvalue

hello
$
```

### Expected behavior
```
$ echo hello | gopass insert mystore/myvalue
$ gopass show -f mystore/myvalue
hello
$
```

### Environment

```
$ gopass --version
gopass 1.10.1 go1.15 darwin amd64
$ uname -v
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
```

- Installation method: brew

**Comment by AnomalRoil** [comment] 2020-09-07 15:11
I cannot test right now, does it do the same if you use the `-a` flag?

`echo hello | gopass insert -a mystore/myvalue`

This is probably related to #788

**Comment by cburgmer** [comment] 2020-09-07 21:25
I tried quite a few combinations of flags, including `-a`, none made any difference.

**Comment by cburgmer** [comment] 2020-09-08 07:55
To clarify, this used to work with 1.9.3, and only recently broke. So it's a regression.

**Comment by dominikschulz** [comment] 2020-09-08 16:05
I don't recall any possible culprits, but it clearly looks like a regression.

However we have at least one open todo wrt. newline handling. That should be addressed as well when we fix this issue.

**Comment by AnomalRoil** [comment] 2020-09-08 22:03
Seems I cannot assign myself to the issue, but I'll look into it as well as the above-mentioned newline handling soon :) (Maybe even this week.)

**Comment by dominikschulz** [comment] 2020-09-09 18:59
Sorry, I don't seem to understand GitHub ACLs.

But thanks for offering to take a look!

**Comment by AnomalRoil** [comment] 2020-09-22 23:42
This is fixed in #1579 by parsing with the secret parser the data that is fed to `insert`.
Notice this means the input is not going to be written "as is" in the secret, instead the password with go to the "Password" field, and so one.

This works  with yaml data and key-value data too. 

Notice that now you need to use `show -o` to display only the password value. 
By default `show -f` will also display the "Password: " key.

**Closed** 2020-09-23 17:43 UTC
Labels: bug

**Comment by thomas-mc-work** [comment] 2020-12-29 19:06
This issue has cost me a couple of hours debugging work until I came here. I'd vote to create a patch release (10.2 or 10.1.1) soon to prevent this headaches from other users. My use case was a batch import. The result was a completely unusable result, as I was unable to fetch a single password afterwards.

**Comment by dominikschulz** [comment] 2021-01-12 13:00
@thomas-mc-work Sorry for that. Please try the 1.11.0 release.
