### ISSUE TITLE
Gopass copy to clipboard does not work since few days under Arch Wayland

### ISSUE THREAD

**Issue by xMordax** [gopasspw/gopass#1347] opened 2020-05-09 10:13 UTC
### Summary
Since some days now, gopass has problems with copying the secret to my clipboard. Usually `gopass -c websites/foo/bar` worked just fine, like the example here https://github.com/gopasspw/gopass/blob/master/docs/features.md#copy-a-secret-to-the-clipboard says, you get a returned message saying `Copied golang.org/gopher to clipboard. Will clear in 45 seconds.`. But now, with the same command, the passwords dos not get copied to my clipboard at all and the only thing I see is, a return in the console, similar, if not the same, to a `gopass show` command.

### Steps To Reproduce
1. Install/Update to latest version of gopass from the Arch respository `community/gopass 1.9.0-2 (5.0 MiB 17.9 MiB)`
2. Create secret
3. Copy the first line of the secret into the clipboard with `gopass -c foo/bar`
4. Try pasting it in some text editor 

### Expected behavior
Get password into the clipboard.

### Environment
- OS: Arch
- OS version: Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux
- Desktop: GNOME
- Display Server: Wayland
- gopass Version: gopass 1.9.0-git+HEAD (2020-05-03 20:29:17) go1.14.2 linux amd64
- Installation method: yay(pacman), package `community/gopass 1.9.0-2 (5.0 MiB 17.9 MiB)`

### Additional context
I don't know what exactly changed, but I tested the gopass bridge in chrome and it still functions normally.

**Comment by dominikschulz** [comment] 2020-05-09 16:29
This is likely a duplicate of #1323.
If I read the arch package changelog correctly it containts the commit right before this was properly fixed.

**Closed** 2020-05-09 16:29 UTC
Labels: duplicate
