### ISSUE TITLE
gopass -c displays secret

### ISSUE THREAD

**Issue by skaldesh** [gopasspw/gopass#1328] opened 2020-05-05 10:30 UTC
### Summary

Using the command `gopass -c my/path/to/secret` displays the secret as well as copying it to the clipboard
### Steps To Reproduce

`gopass -c my/path/to/secret`
### Expected behavior

Only copy password to clipboard, not displaying it
### Environment

- OS: Arch Linux
- OS version: 5.6.10-arch1-1
- gopass Version: gopass 1.9.0-git+HEAD (2020-05-03 20:29:17) go1.14.2 linux amd64
- Installation method: pacman

**Comment by dominikschulz** [comment] 2020-05-05 13:53
This should be a dupe of #1323

**Closed by dominikschulz** 2020-05-05 13:53 UTC
Labels: duplicate
