### ISSUE TITLE
gopass -c Regression in 1.9

### ISSUE THREAD

**Issue by martint17r** [gopasspw/gopass#1341] opened 2020-05-08 10:11 UTC
### Summary
gopass 1.9 returns `2020/05/08 12:03:51 flag provided but not defined: -c` when called with `gopass -c pwentry`

### Expected behavior

prior versions copied the given entry to the clipboard and exited with exit code 0

### Environment

- OS: macOS Catalina
- OS version: Darwin glooper3 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin
- gopass Version: gopass 1.9.0-git+HEAD (2020-05-02 08:27:43) go1.14.2 darwin amd64
<root>     - gpg 2.2.20 - git 2.26.2 -   fs 0.1.0
Available Crypto Backends: gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem

- Installation method: homebrew

### Additional context

I think there is another bug with --clip that prevents the copying to the clipboard from time to time, but I can't reproduce that yet and will open another bug

**Comment by dominikschulz** [comment] 2020-05-08 11:48
Likley a duplicate of #1323.
Otherwise please re-open.

**Closed** 2020-05-08 19:00 UTC
Labels: duplicate
