### ISSUE TITLE
Directory / filename collision when deleting

### ISSUE THREAD

**Issue by deeuu** [gopasspw/gopass#1105] opened 2019-04-24 10:01 UTC
### Summary

Can't delete secret with same name as directory.

### Steps To Reproduce

(edited for brevity)
```
$ gopass list code
├── github
│   └── deeuu
├── gitlab
│   └── deeuu
├── github
└── gitlab

gopass rm code/github                                                                      
Are you sure you would like to delete code/github? [y/N/q]: y
2019/04/24 10:57:53 Cannot remove 'code/github': Is a directory. Use 'gopass rm -r code/github' to delete
```

### Expected behavior
An option (or alternative command) to delete the secret or directory.

### Environment
- Ubuntu 18.04.1 LTS
- 4.15.0-47-generic x86_64
- gopass 1.8.3
- apt-get

**Comment by ndrewtl** [comment] 2019-05-15 00:32
I've also experienced the same issue using gopass `edit`--
```sh
Error: failed to encrypt secret ./secretname: a folder named ./secretname already exists
```

## Environment
- Arch Linux x86_64, Kernel 5.0.13-arch1-1-ARCH
- gopass 1.8.5 (2019-03-13 17:51:51) go1.12 linux amd64

**Comment by martinhoefling** [comment] 2019-07-05 23:25
What would be the expected behavior here? Maybe one also want's prevent the creation of this scenario. What should be deleted first, directory or file?

**Comment by deeuu** [comment] 2019-07-07 12:53
> What should be deleted first, directory or file?

I'd like to be asked a question a long these lines.

Perhaps something like:

> 'X' is both a secret and a directory; delete secret? [y/N/q]:

Then, if N

> Note: use 'gopass rm -r X' to delete the directory.

**Comment by espoelstra** [comment] 2019-08-19 21:46
I've hit this when trying to do a `gopass mv` as well, resulting in fun/weird behaviors. https://github.com/gopasspw/gopass/issues/892#issuecomment-522766342

**Comment by espoelstra** [comment] 2019-11-30 22:01
Did this get fixed?

**Comment by ndrewtl** [comment] 2020-03-01 23:33
Bumping because this should be fixed-- the behavior I'd like to see if there's ambiguity, is for gopass to prompt which, directory or file, you'd like to move/delete/etc. If you don't like the prompt, perhaps a config option should exist about which should be picked if there is ambitguity.

**Closed** 2020-07-17 18:01 UTC
Labels: bug, feature, storage
