### ISSUE TITLE
Special character % getting interpreted strangely

### ISSUE THREAD

**Issue by evincent207** [gopasspw/gopass#1801] opened 2021-02-17 14:24 UTC
### Summary
Passwords containing a % are getting interpreted as '%! (MISSING)'

### Steps To Reproduce
Create a secret with a password containing one or more '%' characters

### Expected behavior
Password treated as plain text

### Environment
Mac OS 11.2
gopass version 1.12.0 go1.15.7 darwin amd64
Installed via brew

### Additional context
Perhaps I am missing something but when I enter passwords using gopass insert -e -f <account> I get this strange behavior:

```
> gopass insert -e -f testaccount
Enter password for testaccount []: my%test%password%
Retype password for testaccount []: my%test%password%
> gopass show testaccount
Secret: testaccount

my%!t(MISSING)est%!p(MISSING)assword%!
(MISSING)
```

**Comment by AnomalRoil** [comment] 2021-02-17 15:29
Yes, this was fixed in #1794.
We're cutting a patch release today to fix it.

I'm closing since this is a duplicate of #1793

**Closed by AnomalRoil** 2021-02-17 15:29 UTC
