### ISSUE TITLE
gopass show --password broken

### ISSUE THREAD

**Issue by r3k2** [gopasspw/gopass#2607] opened 2023-06-16 00:41 UTC
Seems like is broken, I am trying to only get the password as I do with "pass"

```
 gopass show --password url
```
but I get the "Name" field instead of the password field :( 

OS: Arch GNU/Linux
Shell: alacritty
WM: Wayland/Sway

**Comment by dominikschulz** [comment] 2023-06-16 09:54
This should work. I regularly use that feature. Let me try to reproduce.

**Comment by r3k2** [comment] 2023-06-16 14:50
This is the format I have the results when I do a gopass show "name"
```
Name: name.of.entry
Username: here_username
Password: here_password
URL: https://here.url
```
I am starting to suspect the issue is that gopass gets the first line and not the line with Password on it? And such is why I got the name: as a password?
I have around 300 records, if this is the case, is there a way to fix this on all?

**Comment by AnomalRoil** [comment] 2023-06-16 16:23
Ah, does `gopass show name_of_secret password` using our KV feature work?

I think to recall we might have had once upon a time a special case for `--password` pulling from key-values maybe. I'll need to check.

But yeah, worth asking what that flag is supposed to do when you have parsing enabled I guess.

**Comment by r3k2** [comment] 2023-06-16 16:33
hmm interesting with the argument at the end does work, unfortunately most apps ask to be pass compatible and I though gopass was 100% compatible with pass? If I do like in pass a gopass -c name it also gets Name key instead of Password same with the original command I wrote in my first comment. So I think is trying to get the first entries "Name:" as the password so I may need to change the format, is there a way to mass edit or a command to move this around I can write a loop and do it with a bash script

**Comment by r3k2** [comment] 2023-06-16 16:36
ok, so I confirmed I got a ramdon entry and edited with gopass edit name_of_key I copy the Password: key entry and have paste it on top of all the rest of keys as is, and now when I do gopass -c name_of_key it gets the password.

**Comment by dominikschulz** [comment] 2023-06-18 07:58
`pass` did always put the password on the first line of the secret. That's what gopass does at well.
And the import script you linked seems to handle that [correctly](https://github.com/shassard/bitwarden2pass/blob/master/bitwarden2pass.py#L24) as well.

Not sure what went wrong. We might want to fall back checking for a `password` key if the first line is empty. But if it's not empty there is no way for us to tell if the first line is supposed to be the password or not.

**Comment by r3k2** [comment] 2023-07-06 02:19
@AnomalRoil Thanks for the reply! sorry I was out traveling for work. will review your response thanks for the solution.

**Comment by AnomalRoil** [comment] 2023-07-30 17:10
Closing this, feel free to re-open / comment in case you need more help solving the issue. But it looks like the cause is `bitwarden2pass` not conforming with the expected pass output for secrets (e.g. secret on the first line).

**Closed by AnomalRoil** 2023-07-30 17:10 UTC
Labels: bug
