### ISSUE TITLE
First line of file is not stored

### ISSUE THREAD

**Issue by avorima** [gopasspw/gopass#2007] opened 2021-10-08 19:29 UTC
### Summary

I want to use gopass to store my SSH keys, but every time I try to insert them the first line goes missing.

### Steps To Reproduce

```
ssh-keygen -m PEM -b 1024 -t rsa -f key -N ''
cat key | gopass insert mykey
gopass show -n mykey > gopass.key
diff key gopass.key
```

### Expected behavior

The key that is stored in gopass does not differ from the original.

### Environment

- OS version: Linux 5.14.9-arch2-1
- gopass Version: gopass 1.12.8 (2021-08-28 14:31:40) go1.17 linux amd64
- Installation method: pacman

### Additional context

This also occurs when using `gopass insert -m` and then pasting the key.

**Comment by dominikschulz** [comment] 2021-10-09 05:49
Hmm, this is weird. I'll try to reproduce.

But keep in mind that gopass is primarily focused on passwords and insert has some special handing for that.

Did you try piping to gopass cat secret?

**Comment by AnomalRoil** [comment] 2021-10-12 06:29
This still looks like a bug, especially if `-m` also doesn't work because it is supposed to:

> Insert using `$EDITOR` (default: false). This identical to running `gopass edit entry`. All other flags are ignored.

But this issue means that it is not actually equivalent to running `gopass edit entry`... Unless that's also buggy!? (It shouldn't...)

**Comment by dominikschulz** [comment] 2021-12-23 17:21
I have tried to reproduce this today a verified the code paths involved and couldn't

* see how this would fail
* reproduce the failure using the (helpful!) snippet provided:

```
ssh-keygen -m PEM -b 1024 -t rsa -f key -N ''
cat key | gopass insert mykey
gopass show -n mykey > gopass.key
diff key gopass.key
```

So I'm going ahead and close this but please re-open if you can still reproduce this.
In that case please run gopass with `GOPASS_DEBUG_LOG=/tmp/gopass.log`, create throw-away key and provide us with the log output. Thank you.

**Closed by dominikschulz** 2021-12-23 17:21 UTC
Labels: bug

**Comment by avorima** [comment] 2021-12-23 21:14
Yep, it works. Thanks!
