### ISSUE TITLE
default CLI behavior changed and breaks default use-case

### ISSUE THREAD

**Issue by dvzrv** [gopasspw/gopass#1357] opened 2020-05-13 07:55 UTC
### Summary
Since 1.9.1 it is no longer possible to use `gopass <my-secret>` to get the password on stdout as it automatically wants to copy to clipboard. However, in headless environments this fails and returns no password, but only an error message.

### Steps To Reproduce
Install 1.9.1, do `gopass <my-secret>` on a headless remote machine and be greeted with `Error: failed to write to clipboard: exit status 1` and a status code of `11`.

### Expected behavior
The password shows on stdout without any error message or additional text with a status code of 0.

### Environment

- OS: `Arch Linux`
- OS version: `Linux dvzrv 5.6.10.a-1-hardened #1 SMP PREEMPT Sun, 03 May 2020 09:16:44 +0000 x86_64 GNU/Linux`
- gopass Version: `1.9.1`
- Installation method: repo

### Additional context
This change of behavior in a patch level release(!) breaks literally every use-case someone might have had that involves passing a secret via stdout to another application.
Please revert this change and tag another patch level release!

**Comment by dvzrv** [comment] 2020-05-13 07:56
As a follow up: This is also broken for the more explicit `gopass show <my-secret>`.

**Comment by AlexanderThaller** [comment] 2020-05-13 09:39
I have the same issues with gopass show not actually showing the password anymore and just writing a message that the password has been copied to the clipboard.

**Comment by dominikschulz** [comment] 2020-05-13 19:03
Duplicate of #1353

**Closed by dominikschulz** 2020-05-13 19:03 UTC
