### ISSUE TITLE
Zombie process are leaked after pinentry-mac usage

### ISSUE THREAD

**Issue by ncode** [gopasspw/gopass#1874] opened 2021-03-24 11:10 UTC
### Summary
Zombie process after running pinentry-mac

### Steps To Reproduce
```
package main

import (
	"fmt"
	"github.com/gopasspw/gopass/pkg/pinentry"
)

func pin() (pin string, err error) {
	p, err := pinentry.New()
	if err != nil {
		return "", fmt.Errorf("failed to start %q: %w", pinentry.GetBinary(), err)
	}
	defer p.Close()
	p.Set("title", "PIN Prompt")
	p.Set("desc", "Super pin")
	p.Set("prompt", "Please enter your PIN:")
	pin, err := p.GetPin()
	return string(pin), err
}

func main() {
	for {
		p, err := pin()
		if err != nil {
			panic(err)
		}
		fmt.Println(p)
	}
}
```
Run this process in background and input a few pins, open a second shell and run
```
$ ps auxwww | grep pinentry
... 0.0  0.0        0      0   ??  Z    11:38AM   0:00.00 (pinentry-mac)
```
You will see that for each time you typed a password a zombie command is created

### Expected behavior
You type the password and after closing pinentry it exits

### Environment
- OS: Mac OS Catalina and BigSur 
- OS 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
- gopass Version: v1.12.4
- Installation method: using as a library

**Comment by dominikschulz** [comment] 2021-03-24 11:29
Thanks for the comprehensive report.
Will try to reproduce.

**Comment by dominikschulz** [comment] 2021-03-24 13:54
Sorry, at least on Mac I can't reproduce it. After OS upgrade my GPG setup is b0rked again.

```
panic: failed to get pin "/usr/local/opt/pinentry/bin/pinentry": unexpected response: ERR 83918950 Inappropriate ioctl for device <Pinentry>
```

Gosh, I hate GPG ...

**Comment by dominikschulz** [comment] 2021-03-24 14:39
Still can't reproduce on MacOS.
Will try on Linux before closing as invalid.

**Comment by dominikschulz** [comment] 2021-03-24 14:52
Can't reproduce on linux either.

Feel free to reopen if you have more details that would allow me to reproduce the issue.

Please note that we're planning to move this package to github.com/gopasspw/pinentry.

**Closed by dominikschulz** 2021-03-24 14:52 UTC

**Comment by AnomalRoil** [comment] 2021-03-24 17:21
This doesn't seem to work on my mac neither, that's a bad sign IMO @dominikschulz it might mean that pinentry-mac is buggy.

I got a different error tho:
```
panic: unexpected response: ERR 83918950 Inappropriate ioctl for device <Pinentry>
```

**Comment by AnomalRoil** [comment] 2021-03-24 17:30
Might be related?
https://github.com/keybase/keybase-issues/issues/1712#issuecomment-169047174

**Comment by AnomalRoil** [comment] 2021-03-24 18:04
Actually it seems our example client isn't working:  https://github.com/gopasspw/gopass/blob/master/pkg/pinentry/pinentry_test.go

**Comment by dominikschulz** [comment] 2021-03-24 19:26
Sorry, I was in a hurry earlier today. But still I think the conclusion to close this bug (for now) seems correct.

Let me explain my observations:

* `gopass` itself (at least with gpg) seems to work fine, actually we barely use the `pinentry` client - only for the highly experiemental age backend. That's also one of the reasons why I want to move this package to it's own repo. The others being that this is one of a few packages that seem to have some more widespread usage outside of gopass and would deserve proper semantic versioning.
* My Mac (little bit outdated, homebrew not 100% clean state, so maybe not a great specimen) did return `/usr/local/opt/pinentry/pinentry/bin/pinentry` from `gpgconf`. This was actually `pinentry-curses`. I couldn't figure out how to change that (it kept ignoring my change to `$HOME/.gnupg/gpg-agent.conf`, even after reloading the agent, rebooting, etc.) so I changed some symlinks around to actually point to `pinentry-mac`. With that the example code (mostly - some syntactic errors) worked for me and I couldn't reproduce the zombie issue.
* On Linux (Ubuntu 20.10) everything worked just fine, not zombies to be seen either.
* If the issues I've been seeing on Mac are worth filing a Homebrew issue for is not clear to me. My machine isn't in great shape and this might very well be my fault. But if someone with a recent MacOS and a clean Homebrew can reproduce the issue it might make sense for them to file an issue with Homebrew. Or GnuPG.
