### ISSUE TITLE
Copy with gopass -c somesite does not work

### ISSUE THREAD

**Issue by glowinthedark** [gopasspw/gopass#1538] opened 2020-08-18 19:53 UTC
### Summary
Copying a regular password `gopass -c somesite` outputs the following:

```
flag provided but not defined: -c
```

### Steps To Reproduce
`gopass -c somesite`

> NOTE: `gopass otp -c somesite` DOES work as expected.

As a workaround I'm using `"gopass show somesite | head -n 1 | tr -d '\n' | pbcopy"` but this is just too ugly.

### Expected behavior
normal operation

### Environment

- OS: [e.g. Mac OS X 10.15.5 (19F101)]
- OS version: Darwin macbook20.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.10.0-git+HEAD go1.14.2 darwin amd64
- Installation method: `go get -u -v github.com/gopasspw/gopass`

**Comment by dominikschulz** [comment] 2020-08-18 20:32
Does `gopass show -c somesite` work?

**Comment by glowinthedark** [comment] 2020-08-19 07:10
@dominikschulz: indeed, `gopass show -c somesite` works fine. Thanks! 

So then is this the way it is supposed to work?

I think there is a bit of an issue currently with discoverability: `gopass --help` does not display all the available options for all commands so it's practically impossible to figure out the syntax from the built-in help unless we go through the subhelp for each available command, e.g. with `gopass show --help` (or `gopass help show`).

Maybe `--help` should be more verbose and display detailed help for commands too? 

When searching for usage syntax I assume that I would be able to do `--help` and then search for something that matches a search string. This is currently impossible to do in gopass without 'navigating' into specific subcommands.

**Comment by dominikschulz** [comment] 2020-08-19 08:25
Unfortunately I'm not completely sure if we intentionally or accidentally dropped -c from the default action.

We're currently trying to clearly define each command.

**Comment by dominikschulz** [comment] 2020-08-20 05:58
The `-c` flag to the default command (i.e. `gopass entry`) was deprecated in de194f214fbee6bd12c6fd344109d4c78bbed77b.

Please use `gopass show`.

We probably need to improve the help output to make that clear.

**Comment by daraul** [comment] 2020-08-26 09:52
I thought I was losing my mind. I knew `gopass -c somesite` worked earlier this week.

**Comment by mcwienczek** [comment] 2020-08-28 15:13
I also was wondering where did `gopass -c` command go. It is the most common command that I use.

**Comment by dominikschulz** [comment] 2020-08-28 17:56
We did never properly define how each command should behave.
Feel free to contribute to the command definitions in `docs/commands`.

**Comment by oscarpax** [comment] 2020-09-01 21:36
Please bring back `gopass -c somesite`

**Comment by daraul** [comment] 2020-09-01 21:42
At least document the change (if you haven't, I haven't checked myself), and provide some deprecation notice when people use the old command. At least then people have a chance to adjust, as the command simply disappearing can be jarring to some.

**Comment by dominikschulz** [comment] 2020-09-02 17:40
Feel free to open a PR documenting the intended behaviour. If that's merged we will bring it back.

**Comment by daraul** [comment] 2020-09-02 17:53
Oh no, I don't need the old behavior back. :smile: I've already adjusted to the new option.

**Comment by Airblader** [comment] 2020-09-02 17:59
I wasn't affected by this and just stumbled across it, but as a suggestion: for the duration of a release of so such a deprecation could continue to work but print a message to stdout as well about it being deprecated before finally being removed. That would make it discoverable for users as once you use gopass you probably don't read docs all the time.

**Comment by dominikschulz** [comment] 2020-09-02 18:01
@daraul Ok, works for me ;)

I just checked the changelog and we did not mention this, indeed. Sorry. The reason is that this feature didn't exist intentional - it somehow creeped in. That's something we're trying to fix by requiring documentation for future changes.

If anyone else if craving for this feature please open a PR detailing the intended behaviour in `docs/commands/gopass.md` and we can bring it back.

**Comment by Imunhatep** [comment] 2020-09-10 10:12
As `-c` is most used command, why would you even consider an option requireing to tap `show` every time?  Ridiculous decision.
Second, cheat-sheets and demos illustrate usage of -c, and... it does not work.

**Comment by oscarpax** [comment] 2020-09-10 14:53
There is a PR "Re-introduce gopass -c #1572" in the pipe, not merged yet though. So it looks like `-c` is on it's way back along `-u`.

**Comment by dominikschulz** [comment] 2020-09-18 19:39
@Imunhatep How do you want to know that `gopass -c` is the most used command?

**Comment by AnomalRoil** [comment] 2020-09-18 22:04
Fixed by #1572

**Closed by AnomalRoil** 2020-09-18 22:04 UTC
Labels: bug
