### ISSUE TITLE
gopass init --crypto age fails if pgp tools are not installed.

### ISSUE THREAD

**Issue by joe-getcouragenow** [gopasspw/gopass#1655] opened 2020-11-17 15:51 UTC
### Summary

gopass init --crypto age fails if pgp tools such as pinentry-mac  are not installed.

I am using age because for end users its so much easier for them, in that pinentry-mac is not needed.
How about 

### Steps To Reproduce

```
gopass init --crypto age
[init] Initializing a new password store ...

Error: failed to initialize store: failed to read user input: pinentry Error: exec: "pinentry-mac": executable file not found in $PATH
```

### Expected behaviour

Should not require the user to have pinentry-mac, since they are not using pgp as the basis of their crypto.

### Environment

- OS: Mac OS X  Big sur

- OS version: 
uname -a
Darwin x-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

- gopass Version: 
gopass --version
gopass 1.10.1-git+HEAD go1.15.5 darwin amd64
- Installation method: source

### Additional context

Am integrating gopass with sops and age.

**Comment by AnomalRoil** [comment] 2020-11-18 19:11
Seems this is currently by design:
https://github.com/gopasspw/gopass/blob/4d75c3cb477cb789644bff917598eb05d475ea0d/internal/backend/crypto/age/askpass.go#L41

We use pinentry to ask for passwords.

Now the question becomes: should we have an alternative that allows to not have pinentry? 
@dominikschulz  opinion?

**Comment by joe-getcouragenow** [comment] 2020-11-19 09:00
suggest using this : https://github.com/search?l=Go&q=github.com%2FSongmu%2Fprompter&type=Code

looks battle tested.

**Comment by FiloSottile** [comment] 2020-11-19 18:31
FWIW, pinentry-mac does not require gpg and aside from using Assuan as the protocol, is a fairly independent tool.

https://formulae.brew.sh/formula/pinentry-mac

yubikey-agent also depends on pinentry-mac and doesn't use PGP.

**Comment by ckolumbus** [comment] 2020-12-10 19:22
According to my understanding, pinentry and gpg/pgp are completely independent.  The implementation of finding the `pinentry` executable is [quite static in gopass,](https://github.com/gopasspw/gopass/blob/4d75c3cb477cb789644bff917598eb05d475ea0d/pkg/pinentry/pinentry_darwin.go) so one option could be to make it changeable via env variables or some other means. I don't know whether this makes sense under OSX (not much experience there, yet). but at least gpg-agent has a config option for setting the actual pinentry program to switch between gui and terminal pinentry versions. Some programs even have[ internal fall-back](https://unix.stackexchange.com/a/447045) options.

BTW: `brew` let's you install pinentry-mac independently of pgp/gpg.

**Comment by dominikschulz** [comment] 2020-12-12 19:25
pinentry is important for several core use cases, but falling back to reading a password from the command line might be an option. Not sure if I want to add that complexity, but we can consider it.

We wouldn't need to use prompter, we have a helper lib that does the same thing already. But if prompter (or some other lib) proves to be more robust refactoring that might be a new cleanup, too.

**Comment by ckolumbus** [comment] 2020-12-13 17:29
> we have a helper lib that does the same thing already.

Then the easiest would be to  have this as a fallback if no pinentry is found. No need to get new dependencies if something exist.

**Comment by dominikschulz** [comment] 2021-01-12 08:19
I have create #1697, but I'm still not sure if I want to merge this. Let me know what you think.
If you want to have it merged please test it and report if it solves your issue.

**Closed** 2021-01-18 22:02 UTC
Labels: age, bug, help-wanted

**Comment by ckolumbus** [comment] 2021-01-19 08:52
@dominikschulz  some late feedback!

> Let me know what you think.

I looked at #1697 and looks very good to me!
