### ISSUE TITLE
gopass clone deletes previously added pubkey

### ISSUE THREAD

**Issue by tatome** [gopasspw/gopass#2563] opened 2023-02-27 17:21 UTC
### Discussed in https://github.com/gopasspw/gopass/discussions/2561

<div type='discussions-op-text'>

<sup>Originally posted by **tatome** February 21, 2023</sup>
I've set up a git repository, and initialized it as a store for gopass on my home machine.

Then, at work, I created a dedicated gpg key, ran `gopass setup` and then `gopass clone git@some-gitlab/some-repo.git work/some-name`.

This creates a new commit in the local repo that deletes the one public key in `.public-keys` and adds two more (one matching the e-mail address I gave when running `gopass setup` and the one I chose when running `gopass clone`.
Instead, I was expecting it to just add the key I chose when I ran `gopass clone`.

I'm probably just *holding it wrong*™ but I can't find any hints on how to hold it right in the docs or tutorials; they seem to imply that `gopass clone` with a sub store name should just work.

I'm using the gopass version that's currently in the Arch Linux repositories: `gopass 1.15.3 go1.19.5 linux amd64`</div>

**Comment by tatome** [comment] 2023-02-28 15:23
Created a test case: Since I needed multiple users to be sure to replicate the same error, I initialized two GPG homes and keypairs, and wrote a Dockerfile that 

 * creates two users,
 * uses the GPG homes,
 * has one user first initialize a gopass repo, then mount it
 * checks the contents of that user's `.local/share/gopass/stores/shared/.public-keys/`
 * has the other user mount the same shared gopass repo.
 * checks the contents of that other user's `.local/share/gopass/stores/shared/.public-keys/`

Also attached: the output of `docker build .` 
One thing that is surprising is that `.gitattributes` can't be committed, but that doesn't seem to be a fatal error.
More importantly, the key of the first user is removed from the `.public-keys` directory when the second user checks out the repo.

That's not what's supposed to happen, is it?

[gopass-test.txt](https://github.com/gopasspw/gopass/files/10851844/gopass-test.txt)

[test_gopass.tar.gz](https://github.com/gopasspw/gopass/files/10851784/test_gopass.tar.gz)

**Comment by dominikschulz** [comment] 2023-09-11 07:33
This is a duplicate of #2620. Follow along over there for progress.

**Closed by dominikschulz** 2023-09-11 07:33 UTC
Labels: bug
