### ISSUE TITLE
Poor setup experience with age: unable to decrypt secrets

### ISSUE THREAD

**Issue by mykter** [gopasspw/gopass#2333] opened 2022-09-09 17:11 UTC
### Summary

After setting up a new installation with the age backend, I am unable to decrypt any secrets, with the error:
```
❌ Decryption failed: open /Users/mykter/.ssh: no such file or directory

Error: failed to retrieve secret "test": failed to decrypt
```

Indeed, I have no .ssh directory.

### Steps To Reproduce

```
$ brew install gopass
$ gopass setup -crypto age
```
Interlude to hit, find, and fix #1879
```
$ gopass insert test
$ gopass show test
<enter password>
```

### Expected behavior

I can decrypt my entries.

### Environment

- OS: macOS Monterey
- OS version: 21.6.0
- gopass Version: ```
gopass 1.14.5 go1.19 darwin arm64
<root>     -  age 1.0.0 - gitfs 2.32.1```
- Installation method: brew

### Additional context

I have not installed or used age previously on this machine.

**Comment by dominikschulz** [comment] 2022-09-10 06:52
I'm afraid but I'm not sure what's wrong with your setup. I couldn't reproduce (on Linux).

The error message indicates that it's trying to use your SSH keys. Not sure why.
Maybe a MacOS quirk. I'll try to repro on Mac later.

You might want to enable debug logging and - if it's a test store - share the log with us?

Just set `GOPASS_DEBUG_LOG=/some/file/path.log`.

```
$ ./gopass setup -crypto age

   __     _    _ _      _ _   ___   ___
 /'_ '\ /'_'\ ( '_'\  /'_' )/',__)/',__)
( (_) |( (_) )| (_) )( (_| |\__, \\__, \
'\__  |'\___/'| ,__/''\__,_)(____/(____/
( )_) |       | |
 \___/'       (_)

🌟 Welcome to gopass!
🌟 Initializing a new password store ...
🔐 No useable cryptographic keys. Generating new key pair
🧪 Creating cryptographic key pair (age) ...
⚠ Do you want to enter a passphrase? (otherwise we generate one for you) [y/N/q]: y
Enter passphrase for your new keypair: 
Retype passphrase for your new keypair: 
✅ Key pair generated
⚠ 🔐 We need to unlock your newly created private key now! Please enter the passphrase you just generated.
✅ Key pair validated
🔐 Cryptographic keys generated
🌟 Configuring your password store ...
❓ Do you want to add a git remote? [y/N/q]: 
✅ Configuration written to /tmp/gp1/.local/share/gopass/stores/root

$ ./gopass generate test
🚥 Syncing with all remotes ...
[<root>] 
   gitfs pull and push ... Skipped (no remote)
✅ All done
How long should the password be? (q to abort) [24]: 
✅ Password for entry "test" generated
Not printing secrets by default. Use 'gopass show test' to display the password.

$ ./gopass show test
⚠ Parsing is enabled. Use -n to disable.
Secret: test

Uf5XmiezIFEuHqlXtTTsGh6S
```

**Comment by dominikschulz** [comment] 2022-09-18 13:47
@mykter Please provide more information (e.g. your debug log) or we'll have to close this as not-reproducible.

**Comment by dominikschulz** [comment] 2022-09-23 12:19
@zptvreqxyeddzdpa Thanks a lot. This should help me to narrow this down a bit and at least provide some possible mitigations. But I'll need a bit to dive through the logs and see how far I can reproduce it.

**Comment by dominikschulz** [comment] 2022-09-23 12:52
With the debug.log it seems obvious that the implementation assumes that every user has a `.ssh` directory in their home directory. That's very common but apparently not universally true. I'll relax the check to not make it fail.

**Comment by dominikschulz** [comment] 2022-09-23 14:51
I don't think we could blame age here. It's all in our code.

I've now been able to reproduce and verify the fix. Thanks for your help!

**Comment by zptvreqxyeddzdpa** [comment] 2022-09-23 18:35
Thank you for the clarification.

**Closed** 2022-09-24 05:24 UTC
Labels: can-not-reproduce, bug
